### ISSUE TITLE
Why doesn't the Ansible EAP script start the server? 

### ISSUE THREAD

**Issue by alberttwong** [kameshsampath/devops#5]
You install it but why didn't you put in a task to start the server?

**Comment by kameshsampath** [comment]
@alberttwong  the service part is split from the core EAP installation part just for convenience and all service handling part will be done as part of services playbook,  in this way I thought we could have one playbook that handles the services(systemd) related functionalities. having said that the playbook has a control script `eapctl.sh` that gets installed in /usr/local/bin which acts as utility script to start the server.
